[theme]
base = "light"
primaryColor = "#2475fc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans serif"

[server]
headless = true
port = 8501
enableStaticServing = true

[browser]
gatherUsageStats = false
